spring:
  datasource:
    url: jdbc:mysql://${springboot_webapp6_db:localhost}:3306/springboot_book_db
    username: root
    password: M5q@l^#ppt4.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update


